apiVersion: v1
kind: ConfigMap
metadata:
  name: langchain4j-rag-config
  labels:
    app: langchain4j-ai-rag-postgre
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-pgvector:5432/ragdb"
  SPRING_DATASOURCE_USERNAME: "postgres"
